In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from google.colab import files
files.upload()

In [ ]:
df=pd.read_excel('Telco_customer_churn.xlsx')
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [ ]:
df.shape

(7043, 33)

#-Checking Unique Values
First i want to identify the number of unique values each column srepresent so it must be ease to find the non useful columns.

In [ ]:
df.nunique()

CustomerID           7043
Count                   1
Country                 1
State                   1
City                 1129
Zip Code             1652
Lat Long             1652
Latitude             1652
Longitude            1651
Gender                  2
Senior Citizen          2
Partner                 2
Dependents              2
Tenure Months          73
Phone Service           2
Multiple Lines          3
Internet Service        3
Online Security         3
Online Backup           3
Device Protection       3
Tech Support            3
Streaming TV            3
Streaming Movies        3
Contract                3
Paperless Billing       2
Payment Method          4
Monthly Charges      1585
Total Charges        6531
Churn Label             2
Churn Value             2
Churn Score            85
CLTV                 3438
Churn Reason           20
dtype: int64

In [ ]:
df.columns=df.columns.str.lower().str.replace(" ","_").str.strip()
df.columns

Index(['customerid', 'count', 'country', 'state', 'city', 'zip_code',
       'lat_long', 'latitude', 'longitude', 'gender', 'senior_citizen',
       'partner', 'dependents', 'tenure_months', 'phone_service',
       'multiple_lines', 'internet_service', 'online_security',
       'online_backup', 'device_protection', 'tech_support', 'streaming_tv',
       'streaming_movies', 'contract', 'paperless_billing', 'payment_method',
       'monthly_charges', 'total_charges', 'churn_label', 'churn_value',
       'churn_score', 'cltv', 'churn_reason'],
      dtype='object')

#Column Selection
###Here i willl categorize all columns in 3 parts.
target - which have the target variable\
real - it has all the real columns which should be used as it contains all the necessary informations\
drop - all the unnecessary and noisy columns which can confuse the model and doesn't makek any changes.\

###drop columns consist of
identifier - customerid
constans - count ,country\
location - zip_codes , etc\
lekage - churn_score ,cltv (as can be identified after prediction only)

###we will keep
city because it will give us the location of the users and we can use them

In [ ]:
target=df['churn_value']
real=df[['city','gender', 'senior_citizen',
       'partner', 'dependents', 'tenure_months', 'phone_service',
       'multiple_lines', 'internet_service', 'online_security',
       'online_backup', 'device_protection', 'tech_support', 'streaming_tv',
       'streaming_movies', 'contract', 'paperless_billing', 'payment_method','monthly_charges','total_charges','churn_reason']]
drop=df[['customerid','count', 'country', 'state', 'zip_code',
       'lat_long', 'latitude', 'longitude', 'churn_label', 'churn_value',
       'churn_score','cltv']]

In [ ]:
data=pd.concat([real,target],axis=1)
data.head()

,city,gender,senior_citizen,partner,dependents,tenure_months,phone_service,multiple_lines,internet_service,online_security,...,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn_reason,churn_value
0,Los Angeles,Male,No,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Competitor made better offer,1
1,Los Angeles,Female,No,No,Yes,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Moved,1
2,Los Angeles,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,...,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Moved,1
3,Los Angeles,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Moved,1
4,Los Angeles,Male,No,No,Yes,49,Yes,Yes,Fiber optic,No,...,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Competitor had better devices,1

#Removing the duplicates/errors
Sometimes data have duplicate rows which should be removed as can disturb the skewness of data , moreover they can have an empty space which can act as a missing value but we can't fix it with traditional fillna methods thatswhy it has to be replaced with np.nan...

In [ ]:
data=data.replace(['',' '],np.nan)
data.drop_duplicates(inplace=True)

#Dealing with Missing Values

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   city               7043 non-null   object
 1   gender             7043 non-null   object
 2   senior_citizen     7043 non-null   object
 3   partner            7043 non-null   object
 4   dependents         7043 non-null   object
 5   tenure_months      7043 non-null   int64
 6   phone_service      7043 non-null   object
 7   multiple_lines     7043 non-null   object
 8   internet_service   7043 non-null   object
 9   online_security    7043 non-null   object
 10  online_backup      7043 non-null   object
 11  device_protection  7043 non-null   object
 12  tech_support       7043 non-null   object
 13  streaming_tv       7043 non-null   object
 14  streaming_movies   7043 non-null   object
 15  contract           7043 non-null   object
 16  paperless_billing  7043 non-null   object
 17  payment_method     7043 non-null   object
 18  monthly_charges    7043 non-null   float64
 19  total_charges      7032 non-null   float64
 20  churn_reason       1869 non-null   object
 21  churn_value        7043 non-null   int64
dtypes: float64(2), int64(2), object(18)
memory usage: 1.2+ MB

In [ ]:
data.isna().sum()

city                    0
gender                  0
senior_citizen          0
partner                 0
dependents              0
tenure_months           0
phone_service           0
multiple_lines          0
internet_service        0
online_security         0
online_backup           0
device_protection       0
tech_support            0
streaming_tv            0
streaming_movies        0
contract                0
paperless_billing       0
payment_method          0
monthly_charges         0
total_charges          11
churn_reason         5174
churn_value             0
dtype: int64

Here as we can see we have missing values in two columns but we will only deal with **total_charges** because **churn_reason** has only valid reasons for the chustomers who have churned and remaining customers have nan values.

In [ ]:
print(f'total rows in churn_reason: {data.shape[0]}')
print(f'total churned chustomers: {data[data['churn_value']==1].shape[0]}')
print(f'total non churned chustomers: {data[data['churn_value']==0].shape[0]}')
print(f'total missing values in total_charges: {data["churn_reason"].isna().sum()}')
print('hence valid missing values')

total rows in churn_reason: 7043
total churned chustomers: 1869
total non churned chustomers: 5174
total missing values in total_charges: 5174
hence valid missing values

###Replacing The MV in Total Charges

In [ ]:
data[data['total_charges'].isna()].head()

,city,gender,senior_citizen,partner,dependents,tenure_months,phone_service,multiple_lines,internet_service,online_security,...,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn_reason,churn_value
2234,San Bernardino,Female,No,Yes,No,0,No,No phone service,DSL,Yes,...,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,NaN,0
2438,Independence,Male,No,No,No,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,NaN,0
2568,San Mateo,Female,No,Yes,No,0,Yes,No,DSL,Yes,...,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,NaN,0
2667,Cupertino,Male,No,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,NaN,0
2856,Redcrest,Female,No,Yes,No,0,No,No phone service,DSL,Yes,...,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,NaN,0

In [ ]:
data['total_charges'].fillna(data['total_charges'].median(), inplace=True)
data['total_charges'].isna().sum()

np.int64(0)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   city               7043 non-null   object
 1   gender             7043 non-null   object
 2   senior_citizen     7043 non-null   object
 3   partner            7043 non-null   object
 4   dependents         7043 non-null   object
 5   tenure_months      7043 non-null   int64
 6   phone_service      7043 non-null   object
 7   multiple_lines     7043 non-null   object
 8   internet_service   7043 non-null   object
 9   online_security    7043 non-null   object
 10  online_backup      7043 non-null   object
 11  device_protection  7043 non-null   object
 12  tech_support       7043 non-null   object
 13  streaming_tv       7043 non-null   object
 14  streaming_movies   7043 non-null   object
 15  contract           7043 non-null   object
 16  paperless_billing  7043 non-null   object
 17  payment_method     7043 non-null   object
 18  monthly_charges    7043 non-null   float64
 19  total_charges      7043 non-null   float64
 20  churn_reason       1869 non-null   object
 21  churn_value        7043 non-null   int64
dtypes: float64(2), int64(2), object(18)
memory usage: 1.2+ MB

In [ ]:
data.to_csv('Cleaned_Churn_Data.csv',index=False)
files.download('Cleaned_Churn_Data.csv')

In [ ]:
data['churn_value'].value_counts()

churn_value
0    5174
1    1869
Name: count, dtype: int64